/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

export { ReactComponent as Academia } from '../../../svgs/brands/Academia.svg';
export { ReactComponent as Apple } from '../../../svgs/brands/Apple.svg';
export { ReactComponent as Discord } from '../../../svgs/brands/Discord.svg';
export { ReactComponent as Docker } from '../../../svgs/brands/Docker.svg';
export { ReactComponent as Dribbble } from '../../../svgs/brands/Dribbble.svg';
export { ReactComponent as Github } from '../../../svgs/brands/Github.svg';
export { ReactComponent as Gitlab } from '../../../svgs/brands/Gitlab.svg';
export { ReactComponent as Instagram } from '../../../svgs/brands/Instagram.svg';
export { ReactComponent as Opencollective } from '../../../svgs/brands/Opencollective.svg';
export { ReactComponent as Twitch } from '../../../svgs/brands/Twitch.svg';
export { ReactComponent as Twitter } from '../../../svgs/brands/Twitter.svg';
