/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

export { default as angular } from '../../../../svgs/ext/Code/angular.svg';
export { default as bun } from '../../../../svgs/ext/Code/bun.svg';
export { default as c } from '../../../../svgs/ext/Code/c.svg';
export { default as cmake } from '../../../../svgs/ext/Code/cmake.svg';
export { default as cpp } from '../../../../svgs/ext/Code/cpp.svg';
export { default as csharp } from '../../../../svgs/ext/Code/csharp.svg';
export { default as css } from '../../../../svgs/ext/Code/css.svg';
export { default as dartlang } from '../../../../svgs/ext/Code/dartlang.svg';
export { default as go } from '../../../../svgs/ext/Code/go.svg';
export { default as html } from '../../../../svgs/ext/Code/html.svg';
export { default as java } from '../../../../svgs/ext/Code/java.svg';
export { default as js } from '../../../../svgs/ext/Code/js.svg';
export { default as kotlin } from '../../../../svgs/ext/Code/kotlin.svg';
export { default as php } from '../../../../svgs/ext/Code/php.svg';
export { default as py } from '../../../../svgs/ext/Code/py.svg';
export { default as ts } from '../../../../svgs/ext/Code/ts.svg';
export { default as vue } from '../../../../svgs/ext/Code/vue.svg';
