/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

import fda from './fda.mp4';
import mobsdintro from './mobsdintro.mp4';
import sdintro from './sdintro.webm';

export { fda, mobsdintro, sdintro };
