/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

export { ReactComponent as angular } from '../../../../svgs/ext/Code/angular.svg';
export { ReactComponent as bun } from '../../../../svgs/ext/Code/bun.svg';
export { ReactComponent as c } from '../../../../svgs/ext/Code/c.svg';
export { ReactComponent as cmake } from '../../../../svgs/ext/Code/cmake.svg';
export { ReactComponent as cpp } from '../../../../svgs/ext/Code/cpp.svg';
export { ReactComponent as csharp } from '../../../../svgs/ext/Code/csharp.svg';
export { ReactComponent as css } from '../../../../svgs/ext/Code/css.svg';
export { ReactComponent as dartlang } from '../../../../svgs/ext/Code/dartlang.svg';
export { ReactComponent as go } from '../../../../svgs/ext/Code/go.svg';
export { ReactComponent as html } from '../../../../svgs/ext/Code/html.svg';
export { ReactComponent as java } from '../../../../svgs/ext/Code/java.svg';
export { ReactComponent as js } from '../../../../svgs/ext/Code/js.svg';
export { ReactComponent as kotlin } from '../../../../svgs/ext/Code/kotlin.svg';
export { ReactComponent as php } from '../../../../svgs/ext/Code/php.svg';
export { ReactComponent as py } from '../../../../svgs/ext/Code/py.svg';
export { ReactComponent as ts } from '../../../../svgs/ext/Code/ts.svg';
export { ReactComponent as vue } from '../../../../svgs/ext/Code/vue.svg';
