/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

export { default as Academia } from '../../../svgs/brands/Academia.svg';
export { default as Apple } from '../../../svgs/brands/Apple.svg';
export { default as Discord } from '../../../svgs/brands/Discord.svg';
export { default as Docker } from '../../../svgs/brands/Docker.svg';
export { default as Dribbble } from '../../../svgs/brands/Dribbble.svg';
export { default as Github } from '../../../svgs/brands/Github.svg';
export { default as Gitlab } from '../../../svgs/brands/Gitlab.svg';
export { default as Instagram } from '../../../svgs/brands/Instagram.svg';
export { default as Opencollective } from '../../../svgs/brands/Opencollective.svg';
export { default as Twitch } from '../../../svgs/brands/Twitch.svg';
export { default as Twitter } from '../../../svgs/brands/Twitter.svg';
